AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Create an IAM OIDC provider and an IAM role that GitHub Actions can assume via
  OIDC to deploy the Flipkart app. This role will have permissions to push to ECR
  and update ECS services. After deploying, copy the Role ARN and add it to the
  OIDC workflow in GitHub Actions if needed.

Parameters:
  GitHubRepository:
    Type: String
    Description: GitHub repository in the form owner/repo (e.g., myorg/myrepo)

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OpenIDConnectProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub github-actions-deploy-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubRepository}:*
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      Path: /
      Policies:
        - PolicyName: GitHubActionsDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:CreateRepository
                  - ecr:DescribeRepositories
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecs:RegisterTaskDefinition
                  - ecs:UpdateService
                  - ecs:DescribeServices
                  - ecs:ListTaskDefinitions
                Resource: '*'
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

Outputs:
  DeployRoleArn:
    Description: Role ARN that GitHub Actions should assume via OIDC
    Value: !GetAtt [GitHubActionsDeployRole, Arn]
