AWSTemplateFormatVersion: '2010-09-09'
Description: 'Flipkart Clone E-Commerce Application Deployment to AWS'

Parameters:
  EnvironmentName:
    Type: String
    Default: flipkart-clone
    Description: Environment name for the application
  
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 Instance Type
  
  KeyPairName:
    Type: String
    Description: EC2 Key Pair Name for SSH access

Resources:
  # VPC for the application
  AppVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-vpc"

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AppVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-public-subnet"

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-igw"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AppVPC
      InternetGatewayId: !Ref InternetGateway

  # Route Table
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AppVPC
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-rt"

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  # Security Group
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Flipkart Clone
      VpcId: !Ref AppVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-sg"

  # EC2 Instance
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e8a1cbbf3a0dd180  # Amazon Linux 2 (Updated for 2025)
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y nodejs npm git
          
          cd /home/ec2-user
          git clone https://github.com/urbancartcomshop-ui/flipkart-clone.git
          cd flipkart-clone
          npm install
          
          # Start the application
          npm run deploy-server &
          
          # Keep application running with PM2 (optional)
          npm install -g pm2
          pm2 start server-deploy.js --name "flipkart-app"
          pm2 startup
          pm2 save
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-instance"

  # Elastic IP
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref AppInstance
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-eip"

Outputs:
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt AppInstance.PublicIp
  
  ElasticIP:
    Description: Elastic IP address
    Value: !Ref ElasticIP
  
  WebsiteURL:
    Description: URL of the Flipkart Clone application
    Value: !Sub "http://${ElasticIP}"
  
  SSHCommand:
    Description: SSH command to connect to instance
    Value: !Sub "ssh -i your-key.pem ec2-user@${ElasticIP}"
